// Generated by CoffeeScript 1.7.1
(function() {
  var Request, Response, XHR, cleanURL, createError, delay, extend, factory, once,
    __hasProp = {}.hasOwnProperty,
    __slice = [].slice;

  cleanURL = require('./plugins/cleanurl');

  XHR = require('./xhr');

  delay = require('./delay');

  createError = require('./error').create;

  Response = require('./response');

  Request = require('./request');

  extend = require('xtend');

  once = require('once');

  factory = function(defaults, plugins) {
    var http, method, _fn, _i, _len, _ref;
    if (defaults == null) {
      defaults = {};
    }
    if (plugins == null) {
      plugins = [];
    }
    http = function(req, cb) {
      var done, k, plugin, v, xhr, _i, _j, _len, _len1, _ref;
      req = new Request(extend(defaults, req));
      for (_i = 0, _len = plugins.length; _i < _len; _i++) {
        plugin = plugins[_i];
        if (xhr = typeof plugin.createXHR === "function" ? plugin.createXHR(req) : void 0) {
          break;
        }
      }
      if (xhr == null) {
        xhr = new XHR;
      }
      done = once(delay(function(err) {
        var res, _j, _len1;
        xhr.onload = xhr.onerror = xhr.onreadystatechange = xhr.ontimeout = xhr.onprogress = null;
        res = (err != null ? err.isHttpError : void 0) ? err : new Response(req);
        for (_j = 0, _len1 = plugins.length; _j < _len1; _j++) {
          plugin = plugins[_j];
          if (typeof plugin.processResponse === "function") {
            plugin.processResponse(res);
          }
        }
        return cb(err, res);
      }));
      xhr.onreadystatechange = function() {
        if (xhr.readyState === 4) {
          switch (Math.floor(xhr.status / 100)) {
            case 2:
              return done();
            case 4:
              if (xhr.status === 404 && !req.errorOn404) {
                return done();
              } else {
                return done(createError('Client Error', req));
              }
              break;
            case 5:
              return done(createError('Server Error', req));
            default:
              return done(createError('HTTP Error', req));
          }
        }
      };
      xhr.onload = function() {
        return done();
      };
      xhr.onerror = function() {
        return done(createError('Internal XHR Error', req));
      };
      xhr.ontimeout = function() {};
      xhr.onprogress = function() {};
      req.xhr = xhr;
      for (_j = 0, _len1 = plugins.length; _j < _len1; _j++) {
        plugin = plugins[_j];
        if (typeof plugin.processRequest === "function") {
          plugin.processRequest(req);
        }
      }
      xhr.open(req.method, req.url);
      _ref = req.headers;
      for (k in _ref) {
        if (!__hasProp.call(_ref, k)) continue;
        v = _ref[k];
        xhr.setRequestHeader(k, v);
      }
      xhr.send(req.body);
      return req;
    };
    _ref = ['get', 'post', 'put', 'head', 'patch', 'delete'];
    _fn = function(http, method) {
      return http[method] = function(req, cb) {
        req = new Request(req);
        req.method = method;
        return http(req, cb);
      };
    };
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      method = _ref[_i];
      _fn(http, method);
    }
    http.plugins = function() {
      return plugins;
    };
    http.defaults = function(newValues) {
      if (newValues) {
        return factory(extend(defaults, newValues), plugins);
      } else {
        return defaults;
      }
    };
    http.use = function() {
      var newPlugins;
      newPlugins = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      return factory(defaults, plugins.concat(newPlugins));
    };
    http.bare = function() {
      return factory();
    };
    http.Request = Request;
    http.Response = Response;
    return http;
  };

  module.exports = factory({}, [cleanURL]);

}).call(this);
